[tool.poetry]
name = "custom_package"
version = "0.1.2"
description = "Demo Custom Package"
authors = ["MeetParikh01 <meet.parikh@tntra.io>"]

[tool.poetry.dependencies]
python = "^3.8"
SQLAlchemy = "1.4.29"
alembic = "1.7.5"
psycopg2-binary = "2.9.3"
SQLAlchemy-Utils = "0.38.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipython = "^7.31.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
