[tool.poetry]
name = "pdc_session"
version = "0.1.9"
description = "simple shopee session manager"
authors = ["Hfrada <madefrada@gmail.com>"]
readme = "README.md"
packages = [
    { include = "pdc_session" },
]

[tool.poetry.dependencies]
python = "^3.9"
requests = "~2"
eciespy = "^0.3.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
