[tool.poetry]
name = "ccui"
version = "0.2.5"
description = "CatOw's Console User Interface - An interactive Console of tools"
authors = ["CatOw <ccuiproject@gmail.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.9"
rich = "^10.16.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
