[tool.poetry]
name = "power-strip"
version = "0.1.2"
description = ""
authors = ["erdii <me@erdii.engineering>"]

[tool.poetry.dependencies]
python = "^3.9"
grpcio = "^1.43.0"
grpcio-tools = "^1.43.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
