[tool.poetry]
name = "pywordle"
version = "0.1.5"
description = "Little helper to play the Wordle game"
authors = ["Pierre Cart-Grandjean <pcart-grandjea@noreply.com>"]
license = "MIT License"
packages = [{ include = "pywordle" }]
include = [{ path = "pywordle/words", format = "sdist" }]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pytz = "^2021.3"
requests = "^2.26.0"
marshmallow = "^3.14.1"

[tool.poetry.dev-dependencies]
pylint = "^2.12.2"
pytest = "^6.2.5"
black = "^21.12b0"
pdbpp = "^0.10.3"
mypy = "^0.930"
types-pytz = "^2021.3.3"
types-requests = "^2.26.3"
safety = "^1.10.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
wordle = "pywordle.wordle:main"

[tool.mypy]
strict = true
